### ISSUE TITLE
Error trying to compile with plasma 5.21 beta

### ISSUE THREAD

**Issue by andrevmatos** [psifidotos/applet-window-buttons#114]
Trying to compile it on an Arch Linux testing + kde-unstable with plasma 5.21beta (5.20.90), fully up-to-date:
```
Scanning dependencies of target appletdecorationplugin
[ 13%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o
[ 18%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o
[ 22%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/auroraetheme.cpp.o
[ 27%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/buttonsmodel.cpp.o
In file included from /home/andre/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/appletdecorationplugin.cpp:27:
/home/andre/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewclient.h:121:10: error: ‘void Decoration::Applet::PreviewClient::requestShowWindowMenu()’ marked ‘override’, but does not override
  121 |     void requestShowWindowMenu() override;
      |          ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/andre/.cache/yay/plasma5-applets-window-buttons-git/src/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/moc_previewclient.cpp:10,
                 from /home/andre/.cache/yay/plasma5-applets-window-buttons-git/src/build/libappletdecoration/appletdecorationplugin_autogen/mocs_compilation.cpp:11:
/home/andre/.cache/yay/plasma5-applets-window-buttons-git/src/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/../../../../applet-window-buttons/libappletdecoration/previewclient.h:121:10: error: ‘void Decoration::Applet::PreviewClient::requestShowWindowMenu()’ marked ‘override’, but does not override
  121 |     void requestShowWindowMenu() override;
      |          ^~~~~~~~~~~~~~~~~~~~~
[ 31%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/commontools.cpp.o
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:82: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:95: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:535: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by psifidotos** [comment]
Show me please also the earlier compilation step output

**Comment by psifidotos** [comment]
should be fixed now in master

**Comment by andrevmatos** [comment]
Just tried `master`, still getting the error, on Arch Linux kde-unstable up-to-date on plasma 5.21beta
```
...
Scanning dependencies of target appletdecorationplugin
[ 13%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o
In file included from /home/andre/p/github/applet-window-buttons/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/moc_previewclient.cpp:10,
                 from /home/andre/p/github/applet-window-buttons/build/libappletdecoration/appletdecorationplugin_autogen/mocs_compilation.cpp:11:
/home/andre/p/github/applet-window-buttons/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/../../../../libappletdecoration/previewclient.h:115:10: error: ‘void Decoration::Applet::PreviewClient::requestShowWindowMenu()’ marked ‘override’, but does not override
  115 |     void requestShowWindowMenu() override;
      |          ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:82: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:535: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by psifidotos** [comment]
in that case it will have to wait until Plasma 5.21 reaches my Tumbleweed system.

**Comment by rockyprabowo** [comment]
In order to build this applet with Plasma 5.21 beta (Plasma 5.20.90) on Arch Linux I need to change the KDECORATION2_VERSION_MINOR checks from `<=` to `<` because KDECORATION2_VERSION_MINOR follows the Plasma minor versioning so the value would be set to 20, making the checks useless. 
This workaround should be done for the beta releases only because I believe this issue will disappear after 5.21 release.

**Comment by psifidotos** [comment]
yep, this is going to be irrelevant when 5.21 is released in two weeks

**Comment by YamiYukiSenpai** [comment]
> In order to build this applet with Plasma 5.21 beta (Plasma 5.20.90) on Arch Linux I need to change the `KDECORATION2_VERSION_MINOR` checks from `KDECORATION2_VERSION_MINOR <= 20` to `KDECORATION2_VERSION_MINOR < 20` because KDECORATION2_VERSION_MINOR follows the Plasma beta versioning so the value would be set to 20, making the checks useless.
> This workaround should be done for this beta releases only because I believe this issue will disappear after 5.21 is fully released.

Tried that on my KDE Neon Testing Edition.  Didn't work.

**Comment by andrevmatos** [comment]
Current `master` compiling and running fine with Plasma 5.21 final. Thanks

**Comment by skorpions2000** [comment]
rewrite please here https://store.kde.org/p/1272871/ I get from, and have this error...
