### ISSUE TITLE
Fails to build from source on Kubuntu 18.04

### ISSUE THREAD

**Issue by rikmills** [psifidotos/applet-window-buttons#20]
Kubuntu 18.04
GCC 7.3.0
Frameworks 5.44 or 5.47
Qt 5.9.5
Plasma 5.12.6 or 5.12.7

[ 16%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o
In file included from /tmp/buildd/plasma-applet-window-buttons-0.1+git20181114.1249/libappletdecoration/appletdecorationplugin.cpp:26:0:
/tmp/buildd/plasma-applet-window-buttons-0.1+git20181114.1249/libappletdecoration/previewclient.h:103:10: error: 'void Decoration::Applet::PreviewClient::requestShowToolTip(const QString&)' marked 'override', but does not override
     void requestShowToolTip(const QString &text) override;
          ^~~~~~~~~~~~~~~~~~
/tmp/buildd/plasma-applet-window-buttons-0.1+git20181114.1249/libappletdecoration/previewclient.h:104:10: error: 'void Decoration::Applet::PreviewClient::requestHideToolTip()' marked 'override', but does not override
     void requestHideToolTip() override;
          ^~~~~~~~~~~~~~~~~~
libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:62: recipe for target 'libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o' failed
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o] Error 1

**Comment by psifidotos** [comment]
clang?

**Comment by rikmills** [comment]
Forgot to mention. Builds ok with same packaging with 18.10 and 19.04 repos.

**Comment by psifidotos** [comment]
probably the kdecoration version is not enough...

requestHideTooltip
requestShowTooltip

are required from https://github.com/KDE/kdecoration/blob/master/src/private/decoratedclientprivate.h

**Comment by rikmills** [comment]
If that is the case, I would think the min version requirement needs bumping to >= 5.13

**Comment by psifidotos** [comment]
makes sense... This api BTW is meaningless for the applet.

**Comment by psifidotos** [comment]
Can you test? If you remove these two functions it builds OK afterwards?

We could create a Plasma 5.12 specific version

**Comment by psifidotos** [comment]
@rikmills because I want to support plasma 5.12 can you please check that by removing the two in question functions the applet afterwards builds OK? I can even create a separate branch for 5.12 if you want to try...

**Comment by psifidotos** [comment]
I have added two new branches that should be compatible with 5.12

5.12-0.1
5.12-master

please reply if they work ok with plasma 5.12

**Comment by Zardoz89** [comment]
Both compiles correctly, but I get a warning from CMake : 

> -- Found KF5: success (found suitable version "5.44.0", minimum required is "5.26.0") found components:  Plasma WindowSystem I18n Service ConfigWidgets 
> CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/KF5Package/KF5PackageMacros.cmake:26 (message):
>   Deprecated: use kpackage_install_bundled_package
> Call Stack (most recent call first):
>   /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaMacros.cmake:33 (kpackage_install_package)
>   CMakeLists.txt:27 (plasma_install_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by psifidotos** [comment]
Hm... For this am not sure... That warning may indicate that it is installed in wrong place. Do they work ok?

**Comment by Zardoz89** [comment]
I try 5.12-master and looks that works well. 
Sadly lacks, yet, the behaviour options that have applet-window-appmenu

**Comment by psifidotos** [comment]
Open different feature requests if you believe something is missing

**Comment by rikmills** [comment]
> Hm... For this am not sure... That warning may indicate that it is installed in wrong place. Do they work ok?

@psifidotos Sorry, not had time to amend git build script for launchpad or test yet.

By the way, if this repo ever goes to kde git, I would suggest calling it 'plasma-applet-window-buttons
', for both convention and clarity with other KDE repo names. This is also what I would choose to call the package in Ubuntu/Debian with free choice, as I did in [test builds here](https://launchpad.net/~rikmills/+archive/ubuntu/latte-dock).

**Comment by psifidotos** [comment]
there are no plans to make this a KDE project

**Comment by rikmills** [comment]
> there are no plans to make this a KDE project

Oh. To be honest, that lowers this in any testing priority I have. I may still try, but time will be very limited. Thanks for the work all the same. :)
