### ISSUE TITLE
Unable to build: KDE neon, Plasma 5.27.9

### ISSUE THREAD

**Issue by Sadi58** [psifidotos/applet-window-buttons#211]
The applet built earlier this year under **Debian Testing** works well with the latest **Plasma 5.27.9** but I couldn't build it under **KDE neon** after upgrading to Plasma 5.27.9

```
...
[ 68%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewsettings.cpp.o
...
/tmp/applet-window-buttons-master/libappletdecoration/previewbridge.cpp:75:83: error: invalid new-expression of abstract class type ‘Decoration::Applet::PreviewClient’
   75 |     auto ptr = std::unique_ptr<PreviewClient>(new PreviewClient(client, decoration));
...
[ 72%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewshareddecoration.cpp.o
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:216: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:375: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
...
[ 13%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o
...
/tmp/applet-window-buttons-master/libappletdecoration/previewbridge.cpp:75:83: error: invalid new-expression of abstract class type ‘Decoration::Applet::PreviewClient’
   75 |     auto ptr = std::unique_ptr<PreviewClient>(new PreviewClient(client, decoration));
...
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:216: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:375: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by luisbocanegra** [comment]
This is a duplicate of https://github.com/psifidotos/applet-window-buttons/issues/190. 

You need to apply this patch https://github.com/psifidotos/applet-window-buttons/pull/191 before building

**Comment by Sadi58** [comment]
@luisbocanegra Oh, my God, sorry! :-(( I see from #191 that I've gone through this before, and have even showed people (and now myself!) how to do it! :-D
